const colors = require('tailwindcss/colors')

module.exports = {
    purge: [
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/*.js',
        './resources/**/*.vue',
    ],
    darkMode: 'media', // or 'media' or 'class'
    theme: {
        extend: {},
        maxWidth: {
            '1/4': '25%',
            '1/2': '50%',
            '2/3': '66.666667%',
            '3/4': '75%',
            '9/10': '90%',
            '95': '95%',
            '0': '0rem',
            'none': 'none',
            'xs': '20rem',
            'sm': '24rem',
            'md': '28rem',
            'lg': '32rem',
            'xl': '36rem',
            '2xl': '42rem',
            '3xl': '48rem',
            '4xl': '56rem',
            '5xl': '64rem',
            '6xl': '72rem',
            '7xl': '80rem',
            'full': '100%',
            'min': 'min-content',
            'max': 'max-content',
            'prose': '65ch',
            'prose-lg': '100ch',
            'screen-sm': '640px',
            'screen-md': '768px',
            'screen-lg': '1024px',
            'screen-xl': '1280px',
            'screen-2xl': '1536px',
        },
        maxHeight: {
            '95': '95%',
            '0': '0px',
            '0.5': '0.125rem',
            '1': '0.25rem',
            '1.5': '0.375rem',
            '2': '0.5rem',
            '2.5': '0.625rem',
            '3': '0.75rem',
            '3.5': '0.875rem',
            '4': '1rem',
            '5': '1.25rem',
            '6': '1.5rem',
            '7': '1.75rem',
            '8': '2rem',
            '9': '2.25rem',
            '10': '2.5rem',
            '11': '2.75rem',
            '12': '3rem',
            '14': '3.5rem',
            '16': '4rem',
            '20': '5rem',
            '24': '6rem',
            '28': '7rem',
            '32': '8rem',
            '36': '9rem',
            '40': '10rem',
            '44': '11rem',
            '48': '12rem',
            '52': '13rem',
            '56': '14rem',
            '60': '15rem',
            '64': '16rem',
            '72': '18rem',
            '80': '20rem',
            '96': '24rem',
            'px': '1px',
            'full': '100%',
            'screen': '100vh',
        },
        colors: {
            transparent: 'transparent',
            current: 'currentColor',
            black: colors.black,
            white: colors.white,
            gray: colors.trueGray,
            indigo: colors.indigo,
            red: colors.rose,
            yellow: colors.amber,
            secondaryorange: '#ff7300',
            primarynavyblue: '#000e2d',
            drkblue: '#111827',
            medblue: '#001935',
            lhtblue: '#2064C5',
            highlightblue: '#106eea',
            greensuccess: '#00cc00',
            redfail: '#ca1f1f',
            playfulblue: '#d0e5fb',
            bluegray: '#f6f9fe',
            bootgray: '#444444',
            moneygreen: '#279e00',
        },
        listStyleType: {
            alpha: 'lower-alpha',
            disc: 'disc',
        }
    },
    variants: {
        extend: {},
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
}
